<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\State;
use App\Models\Lga;

class LgaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $statesData = [
            [
                "state" => "abia",
                "lgas" => [
                    ["lga" => "aba-north"],
                    ["lga" => "aba-south"],
                    ["lga" => "arochukwu"],
                    ["lga" => "bende"],
                    ["lga" => "ikwuano"],
                    ["lga" => "isiala-ngwa-north"],
                    ["lga" => "isiala-ngwa-south"],
                    ["lga" => "isuikwuato"],
                    ["lga" => "obingwa"],
                    ["lga" => "ohafia"],
                    ["lga" => "osisioma"],
                    ["lga" => "ugwunagbo"],
                    ["lga" => "ukwa-west"],
                    ["lga" => "ukwa-east"],
                    ["lga" => "umu-nneochi"],
                    ["lga" => "umuahia-south"],
                    ["lga" => "umuahia-north"]
                ]
            ],
            [
                "state" => "adamawa",
                "lgas" => [
                    ["lga" => "demsa"],
                    ["lga" => "fufore"],
                    ["lga" => "ganye"],
                    ["lga" => "girei"],
                    ["lga" => "gombi"],
                    ["lga" => "guyuk"],
                    ["lga" => "hong"],
                    ["lga" => "jada"],
                    ["lga" => "lamurde"],
                    ["lga" => "madagali"],
                    ["lga" => "maiha"],
                    ["lga" => "mayo-belwa"],
                    ["lga" => "michika"],
                    ["lga" => "mubi-north"],
                    ["lga" => "mubi-south"],
                    ["lga" => "numan"],
                    ["lga" => "shelleng"],
                    ["lga" => "song"],
                    ["lga" => "toungo"],
                    ["lga" => "yola-north"],
                    ["lga" => "yola-south"]
                ]
            ],
            [
                "state" => "akwa-ibom",
                "lgas" => [
                    ["lga" => "abak"],
                    ["lga" => "eastern-obolo"],
                    ["lga" => "eket"],
                    ["lga" => "esit-eket"],
                    ["lga" => "essien-udim"],
                    ["lga" => "etim-ekpo"],
                    ["lga" => "etinan"],
                    ["lga" => "ibeno"],
                    ["lga" => "ibesikpo-asutan"],
                    ["lga" => "ibiono-ibom"],
                    ["lga" => "ika"],
                    ["lga" => "ikono"],
                    ["lga" => "ikot-abasi"],
                    ["lga" => "ikot-ekpene"],
                    ["lga" => "ini"],
                    ["lga" => "itu"],
                    ["lga" => "mbo"],
                    ["lga" => "mkpat-enin"],
                    ["lga" => "nsit-atai"],
                    ["lga" => "nsit-ibom"],
                    ["lga" => "nsit-ubium"],
                    ["lga" => "obot-akara"],
                    ["lga" => "okobo"],
                    ["lga" => "onna"],
                    ["lga" => "oron"],
                    ["lga" => "oruk-anam"],
                    ["lga" => "udung-uko"],
                    ["lga" => "ukanafun"],
                    ["lga" => "uruan"],
                    ["lga" => "urue-offong-oruko"],
                    ["lga" => "uyo"]
                ]
            ],
            [
                "state" => "anambra",
                "lgas" => [
                    ["lga" => "aguata"],
                    ["lga" => "anambra-east"],
                    ["lga" => "anambra-west"],
                    ["lga" => "anaocha"],
                    ["lga" => "awka-north"],
                    ["lga" => "awka-south"],
                    ["lga" => "ayamelum"],
                    ["lga" => "dunukofia"],
                    ["lga" => "ekwusigo"],
                    ["lga" => "idemili-north"],
                    ["lga" => "idemili-south"],
                    ["lga" => "ihiala"],
                    ["lga" => "njikoka"],
                    ["lga" => "nnewi-north"],
                    ["lga" => "nnewi-south"],
                    ["lga" => "ogbaru"],
                    ["lga" => "onitsha-north"],
                    ["lga" => "onitsha-south"],
                    ["lga" => "orumba-south"],
                    ["lga" => "orumba-north"],
                    ["lga" => "oyi"]
                ]
            ],
            [
                "state" => "abuja",
                "lgas" => [
                    ["lga" => "abaji"],
                    ["lga" => "abuja-municipal"],
                    ["lga" => "bwari"],
                    ["lga" => "gwagwalada"],
                    ["lga" => "kuje"],
                    ["lga" => "kwali"]
                ]
            ],
            [
                "state" => "bauchi",
                "lgas" => [
                    ["lga" => "alkaleri"],
                    ["lga" => "bauchi"],
                    ["lga" => "bogoro"],
                    ["lga" => "dambam"],
                    ["lga" => "darazo"],
                    ["lga" => "dass"],
                    ["lga" => "gamawa"],
                    ["lga" => "ganjuwa"],
                    ["lga" => "giade"],
                    ["lga" => "itas-gadau"],
                    ["lga" => "jama'are"],
                    ["lga" => "katagum"],
                    ["lga" => "kirfi"],
                    ["lga" => "misau"],
                    ["lga" => "ningi"],
                    ["lga" => "shira"],
                    ["lga" => "tafawa-balewa"],
                    ["lga" => "toro"],
                    ["lga" => "warji"],
                    ["lga" => "zaki"]
                ]
            ],
            [
                "state" => "bayelsa",
                "lgas" => [
                    ["lga" => "brass"],
                    ["lga" => "ekeremor"],
                    ["lga" => "kolokuma-opokuma"],
                    ["lga" => "nembe"],
                    ["lga" => "ogbia"],
                    ["lga" => "sagbama"],
                    ["lga" => "southern-ijaw"],
                    ["lga" => "yenagoa"]
                ]
            ],
            [
                "state" => "benue",
                "lgas" => [
                    ["lga" => "ado"],
                    ["lga" => "agatu"],
                    ["lga" => "apa"],
                    ["lga" => "buruku"],
                    ["lga" => "gboko"],
                    ["lga" => "guma"],
                    ["lga" => "gwer-east"],
                    ["lga" => "gwer-west"],
                    ["lga" => "katsina-ala"],
                    ["lga" => "konshisha"],
                    ["lga" => "kwande"],
                    ["lga" => "logo"],
                    ["lga" => "makurdi"],
                    ["lga" => "obi"],
                    ["lga" => "ogbadibo"],
                    ["lga" => "ohimini"],
                    ["lga" => "oju"],
                    ["lga" => "okpokwu"],
                    ["lga" => "otukpo"],
                    ["lga" => "tarka"],
                    ["lga" => "ukum"],
                    ["lga" => "ushongo"],
                    ["lga" => "vandeikya"]
                ]
            ],
            [
                "state" => "borno",
                "lgas" => [
                    ["lga" => "abadam"],
                    ["lga" => "askira-uba"],
                    ["lga" => "bama"],
                    ["lga" => "bayo"],
                    ["lga" => "biu"],
                    ["lga" => "chibok"],
                    ["lga" => "damboa"],
                    ["lga" => "dikwa"],
                    ["lga" => "gubio"],
                    ["lga" => "guzamala"],
                    ["lga" => "gwoza"],
                    ["lga" => "hawul"],
                    ["lga" => "jere"],
                    ["lga" => "kaga"],
                    ["lga" => "kala-balge"],
                    ["lga" => "konduga"],
                    ["lga" => "kukawa"],
                    ["lga" => "kwaya-kusar"],
                    ["lga" => "mafa"],
                    ["lga" => "magumeri"],
                    ["lga" => "maiduguri"],
                    ["lga" => "marte"],
                    ["lga" => "mobbar"],
                    ["lga" => "monguno"],
                    ["lga" => "ngala"],
                    ["lga" => "nganzai"],
                    ["lga" => "shani"]
                ]
            ],
            [
                "state" => "cross-river",
                "lgas" => [
                    ["lga" => "abi"],
                    ["lga" => "akamkpa"],
                    ["lga" => "akpabuyo"],
                    ["lga" => "bakassi"],
                    ["lga" => "bekwarra"],
                    ["lga" => "biase"],
                    ["lga" => "boki"],
                    ["lga" => "calabar-municipality"],
                    ["lga" => "calabar-south"],
                    ["lga" => "etung"],
                    ["lga" => "ikom"],
                    ["lga" => "obanliku"],
                    ["lga" => "obubra"],
                    ["lga" => "obudu"],
                    ["lga" => "odukpani"],
                    ["lga" => "ogoja"],
                    ["lga" => "yakurr"],
                    ["lga" => "yala"]
                ]
            ],
            [
                "state" => "delta",
                "lgas" => [
                    ["lga" => "aniocha-north"],
                    ["lga" => "aniocha-south"],
                    ["lga" => "bomadi"],
                    ["lga" => "burutu"],
                    ["lga" => "ethiope-west"],
                    ["lga" => "ethiope-east"],
                    ["lga" => "ika-north-east"],
                    ["lga" => "ika-south"],
                    ["lga" => "isoko-north"],
                    ["lga" => "isoko-south"],
                    ["lga" => "ndokwa-east"],
                    ["lga" => "ndokwa-west"],
                    ["lga" => "okpe"],
                    ["lga" => "oshimili-north"],
                    ["lga" => "oshimili-south"],
                    ["lga" => "patani"],
                    ["lga" => "sapele"],
                    ["lga" => "udu"],
                    ["lga" => "ughelli-north"],
                    ["lga" => "ughelli-south"],
                    ["lga" => "ukwuani"],
                    ["lga" => "uvwie"],
                    ["lga" => "warri-north"],
                    ["lga" => "warri-south"],
                    ["lga" => "warri-south-west"]
                ]
            ],
            [
                "state" => "ebonyi",
                "lgas" => [
                    ["lga" => "abakaliki"],
                    ["lga" => "afikpo-south"],
                    ["lga" => "afikpo-north"],
                    ["lga" => "ebonyi"],
                    ["lga" => "ezza-north"],
                    ["lga" => "ezza-south"],
                    ["lga" => "ikwo"],
                    ["lga" => "ishielu"],
                    ["lga" => "ivo"],
                    ["lga" => "izzi"],
                    ["lga" => "ohaozara"],
                    ["lga" => "ohaukwu"],
                    ["lga" => "onicha"]
                ]
            ],
            [
                "state" => "edo",
                "lgas" => [
                    ["lga" => "akoko-edo"],
                    ["lga" => "egor"],
                    ["lga" => "esan-central"],
                    ["lga" => "esan-north-east"],
                    ["lga" => "esan-south-east"],
                    ["lga" => "esan-west"],
                    ["lga" => "etsako-west"],
                    ["lga" => "etsako-central"],
                    ["lga" => "etsako-east"],
                    ["lga" => "igueben"],
                    ["lga" => "ikpoba-okha"],
                    ["lga" => "oredo"],
                    ["lga" => "orhionmwon"],
                    ["lga" => "ovia-north-east"],
                    ["lga" => "ovia-south-west"],
                    ["lga" => "owan-east"],
                    ["lga" => "owan-west"],
                    ["lga" => "uhunmwode"]
                ]
            ],
            [
                "state" => "ekiti",
                "lgas" => [
                    ["lga" => "ado-ekiti"],
                    ["lga" => "efon"],
                    ["lga" => "ekiti-east"],
                    ["lga" => "ekiti-south-west"],
                    ["lga" => "ekiti-west"],
                    ["lga" => "emure"],
                    ["lga" => "gbonyin"],
                    ["lga" => "ido-osi"],
                    ["lga" => "ijero"],
                    ["lga" => "ikere"],
                    ["lga" => "ikole"],
                    ["lga" => "ilejemeje"],
                    ["lga" => "irepodun-ifelodun"],
                    ["lga" => "ise-orun"],
                    ["lga" => "moba"],
                    ["lga" => "oye"]
                ]
            ],
            [
                "state" => "enugu",
                "lgas" => [
                    ["lga" => "aninri"],
                    ["lga" => "awgu"],
                    ["lga" => "enugu-east"],
                    ["lga" => "enugu-north"],
                    ["lga" => "enugu-south"],
                    ["lga" => "ezeagu"],
                    ["lga" => "igbo-etiti"],
                    ["lga" => "igbo-eze-north"],
                    ["lga" => "igbo-eze-south"],
                    ["lga" => "isi-uzo"],
                    ["lga" => "nkanu-east"],
                    ["lga" => "nkanu-west"],
                    ["lga" => "nsukka"],
                    ["lga" => "oji-river"],
                    ["lga" => "udenu"],
                    ["lga" => "udi"],
                    ["lga" => "uzo-uwani"]
                ]
            ],
            [
                "state" => "gombe",
                "lgas" => [
                    ["lga" => "akko"],
                    ["lga" => "balanga"],
                    ["lga" => "billiri"],
                    ["lga" => "dukku"],
                    ["lga" => "funakaye"],
                    ["lga" => "gombe"],
                    ["lga" => "kaltungo"],
                    ["lga" => "kwami"],
                    ["lga" => "nafada"],
                    ["lga" => "shongom"],
                    ["lga" => "yalmaltu-deba"]
                ]
            ],
            [
                "state" => "imo",
                "lgas" => [
                    ["lga" => "aboh-mbaise"],
                    ["lga" => "ahiazu-mbaise"],
                    ["lga" => "ehime-mbano"],
                    ["lga" => "ezinihitte-mbaise"],
                    ["lga" => "ideato-north"],
                    ["lga" => "ideato-south"],
                    ["lga" => "ihitte-uboma"],
                    ["lga" => "ikeduru"],
                    ["lga" => "isiala-mbano"],
                    ["lga" => "isu"],
                    ["lga" => "mbaitoli"],
                    ["lga" => "ngor-okpala"],
                    ["lga" => "njaba"],
                    ["lga" => "nkwerre"],
                    ["lga" => "nwangele"],
                    ["lga" => "obowo"],
                    ["lga" => "oguta"],
                    ["lga" => "ohaji-egbema"],
                    ["lga" => "okigwe"],
                    ["lga" => "onuimo"],
                    ["lga" => "orlu"],
                    ["lga" => "orsu"],
                    ["lga" => "oru-east"],
                    ["lga" => "oru-west"],
                    ["lga" => "owerri-north"],
                    ["lga" => "owerri-urban"],
                    ["lga" => "owerri-west"]
                ]
            ],
            [
                "state" => "jigawa",
                "lgas" => [
                    ["lga" => "auyo"],
                    ["lga" => "babura"],
                    ["lga" => "birnin-kudu"],
                    ["lga" => "birniwa"],
                    ["lga" => "buji"],
                    ["lga" => "dutse"],
                    ["lga" => "gagarawa"],
                    ["lga" => "garki"],
                    ["lga" => "gumel"],
                    ["lga" => "guri"],
                    ["lga" => "gwaram"],
                    ["lga" => "gwiwa"],
                    ["lga" => "hadejia"],
                    ["lga" => "jahun"],
                    ["lga" => "kafin-hausa"],
                    ["lga" => "kaugama"],
                    ["lga" => "kazaure"],
                    ["lga" => "kirika-samma"],
                    ["lga" => "kiyawa"],
                    ["lga" => "maigatari"],
                    ["lga" => "malam-madori"],
                    ["lga" => "miga"],
                    ["lga" => "ringim"],
                    ["lga" => "roni"],
                    ["lga" => "sule-tankarkar"],
                    ["lga" => "taura"],
                    ["lga" => "yankwashi"]
                ]
            ],
            [
                "state" => "kaduna",
                "lgas" => [
                    ["lga" => "birnin-gwari"],
                    ["lga" => "chikun"],
                    ["lga" => "giwa"],
                    ["lga" => "igabi"],
                    ["lga" => "ikara"],
                    ["lga" => "jaba"],
                    ["lga" => "jema'a"],
                    ["lga" => "kachia"],
                    ["lga" => "kaduna-north"],
                    ["lga" => "kaduna-south"],
                    ["lga" => "kagarko"],
                    ["lga" => "kajuru"],
                    ["lga" => "kaura"],
                    ["lga" => "kauru"],
                    ["lga" => "kubau"],
                    ["lga" => "kudan"],
                    ["lga" => "lere"],
                    ["lga" => "makarfi"],
                    ["lga" => "sabon-gari"],
                    ["lga" => "sanga"],
                    ["lga" => "soba"],
                    ["lga" => "zangon-kataf"],
                    ["lga" => "zaria"]
                ]
            ],
            [
                "state" => "kano",
                "lgas" => [
                    ["lga" => "ajingi"],
                    ["lga" => "albasu"],
                    ["lga" => "bagwai"],
                    ["lga" => "bebeji"],
                    ["lga" => "bichi"],
                    ["lga" => "bunkure"],
                    ["lga" => "dala"],
                    ["lga" => "danbata"],
                    ["lga" => "dawaki-kudu"],
                    ["lga" => "dawaki-tofa"],
                    ["lga" => "doguwa"],
                    ["lga" => "fagge"],
                    ["lga" => "gabasawa"],
                    ["lga" => "garko"],
                    ["lga" => "garun-malam"],
                    ["lga" => "gaya"],
                    ["lga" => "gezawa"],
                    ["lga" => "gwale"],
                    ["lga" => "gwarzo"],
                    ["lga" => "kabo"],
                    ["lga" => "kano-municipal"],
                    ["lga" => "karaye"],
                    ["lga" => "kibiya"],
                    ["lga" => "kiru"],
                    ["lga" => "kumbotso"],
                    ["lga" => "kunchi"],
                    ["lga" => "kura"],
                    ["lga" => "madobi"],
                    ["lga" => "makoda"],
                    ["lga" => "minjibir"],
                    ["lga" => "nasarawa"],
                    ["lga" => "rano"],
                    ["lga" => "rimin-gado"],
                    ["lga" => "rogo"],
                    ["lga" => "shanono"],
                    ["lga" => "sumaila"],
                    ["lga" => "takai"],
                    ["lga" => "tarauni"],
                    ["lga" => "tofa"],
                    ["lga" => "tsanyawa"],
                    ["lga" => "tudun-wada"],
                    ["lga" => "ungogo"],
                    ["lga" => "warawa"],
                    ["lga" => "wudil"]
                ]
            ],
            [
                "state" => "katsina",
                "lgas" => [
                    ["lga" => "bakori"],
                    ["lga" => "batagarawa"],
                    ["lga" => "batsari"],
                    ["lga" => "baure"],
                    ["lga" => "bindawa"],
                    ["lga" => "charanchi"],
                    ["lga" => "dan-musa"],
                    ["lga" => "dandume"],
                    ["lga" => "danja"],
                    ["lga" => "daura"],
                    ["lga" => "dutsi"],
                    ["lga" => "dutsin-ma"],
                    ["lga" => "faskari"],
                    ["lga" => "funtua"],
                    ["lga" => "ingawa"],
                    ["lga" => "jibia"],
                    ["lga" => "kafur"],
                    ["lga" => "kaita"],
                    ["lga" => "kankara"],
                    ["lga" => "kankia"],
                    ["lga" => "katsina"],
                    ["lga" => "kurfi"],
                    ["lga" => "kusada"],
                    ["lga" => "mai'adua"],
                    ["lga" => "malumfashi"],
                    ["lga" => "mani"],
                    ["lga" => "mashi"],
                    ["lga" => "matazu"],
                    ["lga" => "musawa"],
                    ["lga" => "rimi"],
                    ["lga" => "sabuwa"],
                    ["lga" => "safana"],
                    ["lga" => "sandamu"],
                    ["lga" => "zango"]
                ]
            ],
            [
                "state" => "kebbi",
                "lgas" => [
                    ["lga" => "aliero"],
                    ["lga" => "arewa"],
                    ["lga" => "argungu"],
                    ["lga" => "augie"],
                    ["lga" => "bagudo"],
                    ["lga" => "birnin-kebbi"],
                    ["lga" => "bunza"],
                    ["lga" => "dandi"],
                    ["lga" => "fakai"],
                    ["lga" => "gwandu"],
                    ["lga" => "jega"],
                    ["lga" => "kalgo"],
                    ["lga" => "koko-besse"],
                    ["lga" => "maiyama"],
                    ["lga" => "ngaski"],
                    ["lga" => "sakaba"],
                    ["lga" => "shanga"],
                    ["lga" => "suru"],
                    ["lga" => "wasagu-danko"],
                    ["lga" => "yauri"],
                    ["lga" => "zuru"]
                ]
            ],
            [
                "state" => "kogi",
                "lgas" => [
                    ["lga" => "adavi"],
                    ["lga" => "ajaokuta"],
                    ["lga" => "ankpa"],
                    ["lga" => "bassa"],
                    ["lga" => "dekina"],
                    ["lga" => "ibaji"],
                    ["lga" => "idah"],
                    ["lga" => "igalamela-odolu"],
                    ["lga" => "ijumu"],
                    ["lga" => "kabba-bunu"],
                    ["lga" => "koton-karfe"],
                    ["lga" => "lokoja"],
                    ["lga" => "mopa-muro"],
                    ["lga" => "ofu"],
                    ["lga" => "ogori-magongo"],
                    ["lga" => "okehi"],
                    ["lga" => "okene"],
                    ["lga" => "olamaboro"],
                    ["lga" => "omala"],
                    ["lga" => "yagba-east"],
                    ["lga" => "yagba-west"]
                ]
            ],
            [
                "state" => "kwara",
                "lgas" => [
                    ["lga" => "asa"],
                    ["lga" => "baruten"],
                    ["lga" => "edu"],
                    ["lga" => "ekiti"],
                    ["lga" => "ifelodun"],
                    ["lga" => "ilorin-east"],
                    ["lga" => "ilorin-south"],
                    ["lga" => "ilorin-west"],
                    ["lga" => "irepodun"],
                    ["lga" => "isin"],
                    ["lga" => "kaiama"],
                    ["lga" => "moro"],
                    ["lga" => "offa"],
                    ["lga" => "oke-ero"],
                    ["lga" => "oyun"],
                    ["lga" => "patigi"]
                ]
            ],
            [
                "state" => "lagos",
                "lgas" => [
                    ["lga" => "agege"],
                    ["lga" => "ajeromi-ifelodun"],
                    ["lga" => "alimosho"],
                    ["lga" => "amuwo-odofin"],
                    ["lga" => "apapa"],
                    ["lga" => "badagry"],
                    ["lga" => "epe"],
                    ["lga" => "eti-osa"],
                    ["lga" => "ibeju-lekki"],
                    ["lga" => "ifako-ijaye"],
                    ["lga" => "ikeja"],
                    ["lga" => "ikorodu"],
                    ["lga" => "kosofe"],
                    ["lga" => "lagos-island"],
                    ["lga" => "lagos-mainland"],
                    ["lga" => "mushin"],
                    ["lga" => "ojo"],
                    ["lga" => "oshodi-isolo"],
                    ["lga" => "somolu"],
                    ["lga" => "surulere"]
                ]
            ],
            [
                "state" => "nasarawa",
                "lgas" => [
                    ["lga" => "akwanga"],
                    ["lga" => "awe"],
                    ["lga" => "doma"],
                    ["lga" => "karu"],
                    ["lga" => "keana"],
                    ["lga" => "keffi"],
                    ["lga" => "kokona"],
                    ["lga" => "lafia"],
                    ["lga" => "nasarawa"],
                    ["lga" => "nasarawa-eggon"],
                    ["lga" => "obi"],
                    ["lga" => "toto"],
                    ["lga" => "wamba"]
                ]
            ],
            [
                "state" => "niger",
                "lgas" => [
                    ["lga" => "agaie"],
                    ["lga" => "agwara"],
                    ["lga" => "bida"],
                    ["lga" => "borgu"],
                    ["lga" => "bosso"],
                    ["lga" => "chanchaga"],
                    ["lga" => "edatti"],
                    ["lga" => "gbako"],
                    ["lga" => "gurara"],
                    ["lga" => "katcha"],
                    ["lga" => "kontagora"],
                    ["lga" => "lapai"],
                    ["lga" => "lavun"],
                    ["lga" => "magama"],
                    ["lga" => "mariga"],
                    ["lga" => "mashegu"],
                    ["lga" => "mokwa"],
                    ["lga" => "munya"],
                    ["lga" => "paikoro"],
                    ["lga" => "rafi"],
                    ["lga" => "rijau"],
                    ["lga" => "shiroro"],
                    ["lga" => "suleja"],
                    ["lga" => "tafa"],
                    ["lga" => "wushishi"]
                ]
            ],
            [
                "state" => "ogun",
                "lgas" => [
                    ["lga" => "abeokuta-north"],
                    ["lga" => "abeokuta-south"],
                    ["lga" => "ado-odo-ota"],
                    ["lga" => "ewekoro"],
                    ["lga" => "ifo"],
                    ["lga" => "ijebu-east"],
                    ["lga" => "ijebu-north"],
                    ["lga" => "ijebu-north-east"],
                    ["lga" => "ijebu-ode"],
                    ["lga" => "ikenne"],
                    ["lga" => "imeko-afon"],
                    ["lga" => "ipokia"],
                    ["lga" => "obafemi-owode"],
                    ["lga" => "odeda"],
                    ["lga" => "odogbolu"],
                    ["lga" => "ogun-water-side"],
                    ["lga" => "remo-north"],
                    ["lga" => "sagamu"],
                    ["lga" => "yewa-egbado-north"],
                    ["lga" => "yewa-egbado-south"]
                ]
            ],
            [
                "state" => "ondo",
                "lgas" => [
                    ["lga" => "akoko-north-east"],
                    ["lga" => "akoko-north-west"],
                    ["lga" => "akoko-south-east"],
                    ["lga" => "akoko-south-west"],
                    ["lga" => "akure-north"],
                    ["lga" => "akure-south"],
                    ["lga" => "ese-odo"],
                    ["lga" => "idanre"],
                    ["lga" => "ifedore"],
                    ["lga" => "ilaje"],
                    ["lga" => "ileoluji-okeigbo"],
                    ["lga" => "irele"],
                    ["lga" => "odigbo"],
                    ["lga" => "okitipupa"],
                    ["lga" => "ondo-east"],
                    ["lga" => "ondo-west"],
                    ["lga" => "ose"],
                    ["lga" => "owo"]
                ]
            ],
            [
                "state" => "osun",
                "lgas" => [
                    ["lga" => "atakumosa-east"],
                    ["lga" => "atakumosa-west"],
                    ["lga" => "ayedaade"],
                    ["lga" => "ayedire"],
                    ["lga" => "boluwaduro"],
                    ["lga" => "boripe"],
                    ["lga" => "ede-north"],
                    ["lga" => "ede-south"],
                    ["lga" => "egbedore"],
                    ["lga" => "ejigbo"],
                    ["lga" => "ife-central"],
                    ["lga" => "ife-east"],
                    ["lga" => "ife-north"],
                    ["lga" => "ife-south"],
                    ["lga" => "ifedayo"],
                    ["lga" => "ifelodun"],
                    ["lga" => "ila"],
                    ["lga" => "ilesa-east"],
                    ["lga" => "ilesa-west"],
                    ["lga" => "irepodun"],
                    ["lga" => "irewole"],
                    ["lga" => "isokan"],
                    ["lga" => "iwo"],
                    ["lga" => "obokun"],
                    ["lga" => "odo-otin"],
                    ["lga" => "ola-oluwa"],
                    ["lga" => "olorunda"],
                    ["lga" => "oriade"],
                    ["lga" => "orolu"],
                    ["lga" => "osogbo"]
                ]
            ],
            [
                "state" => "oyo",
                "lgas" => [
                    ["lga" => "afijio"],
                    ["lga" => "akinyele"],
                    ["lga" => "atiba"],
                    ["lga" => "atisbo"],
                    ["lga" => "egbeda"],
                    ["lga" => "ibadan-north"],
                    ["lga" => "ibadan-north-east"],
                    ["lga" => "ibadan-north-west"],
                    ["lga" => "ibadan-south-west"],
                    ["lga" => "ibadan-south-east"],
                    ["lga" => "ibarapa-central"],
                    ["lga" => "ibarapa-east"],
                    ["lga" => "ibarapa-north"],
                    ["lga" => "ido"],
                    ["lga" => "irepo"],
                    ["lga" => "iseyin"],
                    ["lga" => "itesiwaju"],
                    ["lga" => "iwajowa"],
                    ["lga" => "kajola"],
                    ["lga" => "lagelu"],
                    ["lga" => "ogbomoso-north"],
                    ["lga" => "ogbomoso-south"],
                    ["lga" => "ogo-oluwa"],
                    ["lga" => "olorunsogo"],
                    ["lga" => "oluyole"],
                    ["lga" => "ona-ara"],
                    ["lga" => "orelope"],
                    ["lga" => "ori-ire"],
                    ["lga" => "oyo-east"],
                    ["lga" => "oyo-west"],
                    ["lga" => "saki-east"],
                    ["lga" => "saki-west"],
                    ["lga" => "surulere"]
                ]
            ],
            [
                "state" => "plateau",
                "lgas" => [
                    ["lga" => "barikin-ladi"],
                    ["lga" => "bassa"],
                    ["lga" => "bokkos"],
                    ["lga" => "jos-east"],
                    ["lga" => "jos-north"],
                    ["lga" => "jos-south"],
                    ["lga" => "kanam"],
                    ["lga" => "kanke"],
                    ["lga" => "langtang-north"],
                    ["lga" => "langtang-south"],
                    ["lga" => "mangu"],
                    ["lga" => "mikang"],
                    ["lga" => "pankshin"],
                    ["lga" => "qua'an-pan"],
                    ["lga" => "riyom"],
                    ["lga" => "shendam"],
                    ["lga" => "wase"]
                ]
            ],
            [
                "state" => "rivers",
                "lgas" => [
                    ["lga" => "abua-odual"],
                    ["lga" => "ahoada-east"],
                    ["lga" => "ahoada-west"],
                    ["lga" => "akuku-toru"],
                    ["lga" => "andoni"],
                    ["lga" => "asari-toru"],
                    ["lga" => "bonny"],
                    ["lga" => "degema"],
                    ["lga" => "eleme"],
                    ["lga" => "emohua"],
                    ["lga" => "etche"],
                    ["lga" => "gokana"],
                    ["lga" => "ikwerre"],
                    ["lga" => "khana"],
                    ["lga" => "obio-akpor"],
                    ["lga" => "ogba-egbema-ndoni"],
                    ["lga" => "ogu-bolo"],
                    ["lga" => "okrika"],
                    ["lga" => "omuma"],
                    ["lga" => "opobo-nkoro"],
                    ["lga" => "oyigbo"],
                    ["lga" => "port-harcourt"],
                    ["lga" => "tai"]
                ]
            ],
            [
                "state" => "sokoto",
                "lgas" => [
                    ["lga" => "binji"],
                    ["lga" => "bodinga"],
                    ["lga" => "dange-shuni"],
                    ["lga" => "gada"],
                    ["lga" => "goronyo"],
                    ["lga" => "gudu"],
                    ["lga" => "gwadabawa"],
                    ["lga" => "illela"],
                    ["lga" => "isa"],
                    ["lga" => "kebbe"],
                    ["lga" => "kware"],
                    ["lga" => "rabah"],
                    ["lga" => "sabon-birni"],
                    ["lga" => "shagari"],
                    ["lga" => "silame"],
                    ["lga" => "sokoto-north"],
                    ["lga" => "sokoto-south"],
                    ["lga" => "tambuwal"],
                    ["lga" => "tangaza"],
                    ["lga" => "tureta"],
                    ["lga" => "wamakko"],
                    ["lga" => "wurno"],
                    ["lga" => "yabo"]
                ]
            ],
            [
                "state" => "taraba",
                "lgas" => [
                    ["lga" => "ardo-kola"],
                    ["lga" => "bali"],
                    ["lga" => "donga"],
                    ["lga" => "gashaka"],
                    ["lga" => "gassol"],
                    ["lga" => "ibi"],
                    ["lga" => "jalingo"],
                    ["lga" => "karim-lamido"],
                    ["lga" => "kurmi"],
                    ["lga" => "lau"],
                    ["lga" => "sardauna"],
                    ["lga" => "takum"],
                    ["lga" => "ussa"],
                    ["lga" => "wukari"],
                    ["lga" => "yorro"],
                    ["lga" => "zing"]
                ]
            ],
            [
                "state" => "yobe",
                "lgas" => [
                    ["lga" => "bade"],
                    ["lga" => "bursari"],
                    ["lga" => "damaturu"],
                    ["lga" => "fika"],
                    ["lga" => "fune"],
                    ["lga" => "geidam"],
                    ["lga" => "gujba"],
                    ["lga" => "gulani"],
                    ["lga" => "jakusko"],
                    ["lga" => "karasuwa"],
                    ["lga" => "machina"],
                    ["lga" => "nangere"],
                    ["lga" => "nguru"],
                    ["lga" => "potiskum"],
                    ["lga" => "tarmuwa"],
                    ["lga" => "yunusari"],
                    ["lga" => "yusufari"]
                ]
            ],
            [
                "state" => "zamfara",
                "lgas" => [
                    ["lga" => "anka"],
                    ["lga" => "bakura"],
                    ["lga" => "birnin-magaji"],
                    ["lga" => "bukkuyum"],
                    ["lga" => "bungudu"],
                    ["lga" => "gummi"],
                    ["lga" => "gusau"],
                    ["lga" => "kaura-namoda"],
                    ["lga" => "maradun"],
                    ["lga" => "maru"],
                    ["lga" => "shinkafi"],
                    ["lga" => "talata-mafara"],
                    ["lga" => "tsafe"],
                    ["lga" => "zurmi"]
                ]
            ]
        ];

        foreach ($statesData as $stateData) {
            $state = State::where('name', $stateData['state'])->first();

            if ($state) {
                foreach ($stateData['lgas'] as $lgaData) {
                    Lga::create([
                        'state_id' => $state->state_id,
                        'name' => $lgaData['lga']
                    ]);
                }
            }
        }
    }
}
