<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolesAndPermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Reset cached roles and permissions
        app()['cache']->forget('spatie.permission.cache');

        // Create permissions for all actions in the application
        $permissions = [
            // Employee Management
            'view_employees',
            'create_employees',
            'edit_employees',
            'delete_employees',
            'manage_employees', // existing - for backward compatibility

            // Department Management
            'view_departments',
            'create_departments',
            'edit_departments',
            'delete_departments',
            'manage_departments', // existing - for backward compatibility

            // Payroll Management
            'view_payroll',
            'create_payroll',
            'edit_payroll',
            'delete_payroll',
            'manage_payroll', // existing - for backward compatibility
            'generate_payroll',
            'approve_payroll',
            'view_payslips',
            'manage_payroll_adjustments',

            // User Management
            'view_users',
            'create_users',
            'edit_users',
            'delete_users',
            'manage_users', // existing - for backward compatibility
            'reset_user_passwords',

            // Biometric Management
            'view_biometrics',
            'create_biometrics',
            'edit_biometrics',
            'delete_biometrics',
            'manage_biometrics', // existing - for backward compatibility
            // Specific biometric permissions used in controller
            'view_biometric_data',
            'create_biometric_data',

            // Disciplinary Management
            'view_disciplinary',
            'create_disciplinary',
            'edit_disciplinary',
            'delete_disciplinary',
            'manage_disciplinary', // existing - for backward compatibility
            // Specific disciplinary permissions used in controller
            'view_disciplinary_actions',
            'create_disciplinary_actions',
            'edit_disciplinary_actions',
            'delete_disciplinary_actions',

            // SMS Management
            'view_sms',
            'send_sms',
            'manage_sms', // existing - for backward compatibility
            // Specific SMS permissions used in controller
            'view_sms_notifications',
            'create_sms_notifications',

            // Retirement Management
            'view_retirement',
            'create_retirement',
            'edit_retirement',
            'delete_retirement',
            'manage_retirement', // existing - for backward compatibility
            // Specific retirement permissions used in controller
            'view_retirements',
            'create_retirements',

            // Report Management
            'view_reports',
            'generate_reports',
            'manage_reports', // existing - for backward compatibility

            // Audit Trail Management
            'view_audit_logs',

            // Employee Change Management
            'approve_employee_changes',
            'manage_employee_changes',
            'view_pending_employee_changes',
            'approve_pending_employee_changes',
            'reject_pending_employee_changes',
            'approve_bank_details',
            'manage_bank_details',

            // Deduction Management
            'view_deductions',
            'create_deductions',
            'edit_deductions',
            'delete_deductions',
            'manage_deductions',

            // Addition Management
            'view_additions',
            'create_additions',
            'edit_additions',
            'delete_additions',
            'manage_additions',

            // Pensioner Management
            'view_pensioners',
            'create_pensioners',
            'edit_pensioners',
            'delete_pensioners',
            'manage_pensioners',

            // Role Management
            'view_roles',
            'create_roles',
            'edit_roles',
            'delete_roles',
            'manage_roles',

            // Grade Level Management
            'view_grade_levels',
            'create_grade_levels',
            'edit_grade_levels',
            'delete_grade_levels',
            'manage_grade_levels',

            // Salary Scale Management
            'view_salary_scales',
            'create_salary_scales',
            'edit_salary_scales',
            'delete_salary_scales',
            'manage_salary_scales',

            // Cadre Management
            'view_cadres',
            'create_cadres',
            'edit_cadres',
            'delete_cadres',
            'manage_cadres',

            // Designation Management
            'view_designations',
            'create_designations',
            'edit_designations',
            'delete_designations',
            'manage_designations',

            // Addition Type Management
            'view_addition_types',
            'create_addition_types',
            'edit_addition_types',
            'delete_addition_types',
            'manage_addition_types',

            // Deduction Type Management
            'view_deduction_types',
            'create_deduction_types',
            'edit_deduction_types',
            'delete_deduction_types',
            'manage_deduction_types',

            // Payment Management
            'view_payments',
            'create_payments',
            'edit_payments',
            'delete_payments',
            'manage_payments',

            // Promotion Management
            'view_promotions',
            'create_promotions',
            'edit_promotions',
            'delete_promotions',
            'manage_promotions',
            'approve_promotions',
            'reject_promotions',

            // Probation Management
            'view_probation',
            'manage_probation',
            'approve_probation',
            'reject_probation',
            'start_probation',
            'extend_probation',

            // Profile Management
            'view_profile',
            'edit_profile',
            'change_password',

            // Payroll Bulk Actions
            'bulk_send_payroll_for_review',
            'bulk_mark_payroll_as_reviewed',
            'bulk_send_payroll_for_approval',
            'bulk_final_approve_payroll',
            'bulk_update_payroll_status',

            // Loan Management
            'view_loans',
            'create_loans',
            'edit_loans',
            'delete_loans',
            'manage_loans',

            // Grade Level Adjustment Management
            'view_grade_level_adjustments',
            'create_grade_level_adjustments',
            'delete_grade_level_adjustments',

            // Leave Management
            'view_leaves',
            'create_leaves',
            'edit_leaves',
            'delete_leaves',
            'manage_leaves',
            'approve_leaves',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission]);
        }

        // Create roles and assign permissions
        // Admin role - has all permissions
        $adminRole = Role::firstOrCreate(['name' => 'admin']);
        $adminRole->givePermissionTo([
            'view_employees',
            'create_employees',
            'edit_employees',
            'delete_employees',
            'manage_employees',
            'view_departments',
            'create_departments',
            'edit_departments',
            'delete_departments',
            'manage_departments',
            'view_payroll',
            'create_payroll',
            'edit_payroll',
            'delete_payroll',
            'manage_payroll',
            'generate_payroll',
            'approve_payroll',
            'view_payslips',
            'manage_payroll_adjustments',
            'view_users',
            'create_users',
            'edit_users',
            'delete_users',
            'manage_users',
            'reset_user_passwords',
            'view_biometrics',
            'create_biometrics',
            'edit_biometrics',
            'delete_biometrics',
            'manage_biometrics',
            'view_biometric_data',
            'create_biometric_data',
            'view_disciplinary',
            'create_disciplinary',
            'edit_disciplinary',
            'delete_disciplinary',
            'manage_disciplinary',
            'view_disciplinary_actions',
            'create_disciplinary_actions',
            'edit_disciplinary_actions',
            'delete_disciplinary_actions',
            'view_sms',
            'send_sms',
            'manage_sms',
            'view_sms_notifications',
            'create_sms_notifications',
            'view_retirement',
            'create_retirement',
            'edit_retirement',
            'delete_retirement',
            'manage_retirement',
            'view_retirements',
            'create_retirements',
            'view_reports',
            'generate_reports',
            'manage_reports',
            'view_audit_logs',
            'approve_employee_changes',
            'manage_employee_changes',
            'view_pending_employee_changes',
            'approve_pending_employee_changes',
            'reject_pending_employee_changes',
            'approve_bank_details',
            'manage_bank_details',
            'view_deductions',
            'create_deductions',
            'edit_deductions',
            'delete_deductions',
            'manage_deductions',
            'view_additions',
            'create_additions',
            'edit_additions',
            'delete_additions',
            'manage_additions',
            'view_pensioners',
            'create_pensioners',
            'edit_pensioners',
            'delete_pensioners',
            'manage_pensioners',
            'view_roles',
            'create_roles',
            'edit_roles',
            'delete_roles',
            'manage_roles',
            'view_grade_levels',
            'create_grade_levels',
            'edit_grade_levels',
            'delete_grade_levels',
            'manage_grade_levels',
            'view_salary_scales',
            'create_salary_scales',
            'edit_salary_scales',
            'delete_salary_scales',
            'manage_salary_scales',
            'view_cadres',
            'create_cadres',
            'edit_cadres',
            'delete_cadres',
            'manage_cadres',
            'view_designations',
            'create_designations',
            'edit_designations',
            'delete_designations',
            'manage_designations',
            'view_addition_types',
            'create_addition_types',
            'edit_addition_types',
            'delete_addition_types',
            'manage_addition_types',
            'view_deduction_types',
            'create_deduction_types',
            'edit_deduction_types',
            'delete_deduction_types',
            'manage_deduction_types',
            'view_payments',
            'create_payments',
            'edit_payments',
            'delete_payments',
            'manage_payments',
            'view_promotions',
            'create_promotions',
            'edit_promotions',
            'delete_promotions',
            'manage_promotions',
            'approve_promotions',
            'reject_promotions',
            'view_profile',
            'edit_profile',
            'change_password',
            'bulk_send_payroll_for_review',
            'bulk_mark_payroll_as_reviewed',
            'bulk_send_payroll_for_approval',
            'bulk_final_approve_payroll',
            'bulk_update_payroll_status',
            'view_loans',
            'create_loans',
            'edit_loans',
            'delete_loans',
            'manage_loans',
            'view_grade_level_adjustments',
            'create_grade_level_adjustments',
            'delete_grade_level_adjustments',
            'view_leaves',
            'create_leaves',
            'edit_leaves',
            'delete_leaves',
            'manage_leaves',
            'approve_leaves',
            'view_probation',
            'manage_probation',
            'approve_probation',
            'reject_probation',
            'start_probation',
            'extend_probation',
        ]);

        // Admin II role
        $adminII = Role::firstOrCreate(['name' => 'admin II']);
        $adminII->givePermissionTo([
            'view_employees',
            'create_employees',
            'edit_employees',
            'delete_employees',
            'manage_employees',
            'view_departments',
            'create_departments',
            'edit_departments',
            'delete_departments',
            'manage_departments',
            'view_users',
            'create_users',
            'edit_users',
            'delete_users',
            'manage_users',
            'reset_user_passwords',
            'view_biometrics',
            'create_biometrics',
            'edit_biometrics',
            'delete_biometrics',
            'manage_biometrics',
            'view_biometric_data',
            'create_biometric_data',
            'view_disciplinary',
            'create_disciplinary',
            'edit_disciplinary',
            'delete_disciplinary',
            'manage_disciplinary',
            'view_disciplinary_actions',
            'create_disciplinary_actions',
            'edit_disciplinary_actions',
            'delete_disciplinary_actions',
            'view_sms',
            'send_sms',
            'manage_sms',
            'view_sms_notifications',
            'create_sms_notifications',
            'view_retirement',
            'edit_retirement',
            'manage_retirement',
            'view_retirements',
            'view_reports',
            'generate_reports',
            'manage_reports',
            'view_audit_logs',
            'approve_employee_changes',
            'view_pending_employee_changes',
            'reject_pending_employee_changes',
            'view_pensioners',
            'create_pensioners',
            'edit_pensioners',
            'manage_pensioners',
            'view_roles',
            'create_roles',
            'edit_roles',
            'delete_roles',
            'manage_roles',
            'view_salary_scales',
            'create_salary_scales',
            'edit_salary_scales',
            'delete_salary_scales',
            'manage_salary_scales',
            'view_promotions',
            'create_promotions',
            'edit_promotions',
            'delete_promotions',
            'manage_promotions',
            'approve_promotions',
            'reject_promotions',
            'view_profile',
            'edit_profile',
            'change_password',
            'view_loans',
            'manage_loans',
            'view_leaves',
            'create_leaves',
            'edit_leaves',
            'delete_leaves',
            'manage_leaves',
            'view_probation',
            'manage_probation',
            'approve_probation',
            'reject_probation',
            'start_probation',
            'extend_probation',
        ]);

        // Initiator II role
        $initiatorII = Role::firstOrCreate(['name' => 'Initiator II']);
        $initiatorII->givePermissionTo([
            'view_employees',
            'manage_employees',
            'view_departments',
            'manage_departments',
            'view_payroll',
            'create_payroll',
            'edit_payroll',
            'delete_payroll',
            'manage_payroll',
            'generate_payroll',
            'view_payslips',
            'manage_payroll_adjustments',
            'view_disciplinary',
            'manage_disciplinary',
            'view_disciplinary_actions',
            'view_retirement',
            'manage_retirement',
            'view_retirements',
            'view_reports',
            'generate_reports',
            'manage_reports',
            'view_audit_logs',
            'view_deductions',
            'create_deductions',
            'edit_deductions',
            'delete_deductions',
            'manage_deductions',
            'view_additions',
            'create_additions',
            'edit_additions',
            'delete_additions',
            'manage_additions',
            'view_pensioners',
            'manage_pensioners',
            'view_grade_levels',
            'create_grade_levels',
            'edit_grade_levels',
            'delete_grade_levels',
            'manage_grade_levels',
            'view_salary_scales',
            'create_salary_scales',
            'edit_salary_scales',
            'delete_salary_scales',
            'manage_salary_scales',
            'view_addition_types',
            'create_addition_types',
            'edit_addition_types',
            'delete_addition_types',
            'manage_addition_types',
            'view_deduction_types',
            'create_deduction_types',
            'edit_deduction_types',
            'delete_deduction_types',
            'manage_deduction_types',
            'view_payments',
            'view_promotions',
            'manage_promotions',
            'view_profile',
            'change_password',
            'bulk_send_payroll_for_review',
            'bulk_mark_payroll_as_reviewed',
            'bulk_update_payroll_status',
            'view_loans',
            'create_loans',
            'edit_loans',
            'delete_loans',
            'manage_loans',
            'view_grade_level_adjustments',
            'create_grade_level_adjustments',
            'delete_grade_level_adjustments',
            'manage_bank_details',
        ]);

        // Initiator role
        $initiator = Role::firstOrCreate(['name' => 'Initiator']);
        $initiator->givePermissionTo([
            'view_employees',
            'manage_employees',
            'view_departments',
            'manage_departments',
            'view_payroll',
            'manage_payroll',
            'view_payslips',
            'view_disciplinary',
            'manage_disciplinary',
            'view_disciplinary_actions',
            'view_retirement',
            'manage_retirement',
            'view_retirements',
            'view_reports',
            'generate_reports',
            'manage_reports',
            'view_audit_logs',
            'view_deductions',
            'manage_deductions',
            'view_additions',
            'manage_additions',
            'view_pensioners',
            'manage_pensioners',
            'view_grade_levels',
            'manage_grade_levels',
            'view_salary_scales',
            'manage_salary_scales',
            'view_addition_types',
            'manage_addition_types',
            'view_deduction_types',
            'manage_deduction_types',
            'view_profile',
            'change_password',
            'bulk_mark_payroll_as_reviewed',
            'bulk_send_payroll_for_approval',
            'view_loans',
            'manage_loans',
            'view_grade_level_adjustments',
            'manage_bank_details',
            'approve_bank_details',
        ]);

        // Admin I role
        $adminI = Role::firstOrCreate(['name' => 'admin I']);
        $adminI->givePermissionTo([
            'view_employees',
            'manage_employees',
            'view_departments',
            'manage_departments',
            'view_users',
            'manage_users',
            'view_biometrics',
            'manage_biometrics',
            'view_biometric_data',
            'view_disciplinary',
            'manage_disciplinary',
            'view_sms',
            'send_sms',
            'manage_sms',
            'view_sms_notifications',
            'create_sms_notifications',
            'view_retirement',
            'create_retirement',
            'edit_retirement',
            'delete_retirement',
            'manage_retirement',
            'view_retirements',
            'view_reports',
            'generate_reports',
            'manage_reports',
            'view_audit_logs',
            'approve_employee_changes',
            'manage_employee_changes',
            'view_pending_employee_changes',
            'approve_pending_employee_changes',
            'reject_pending_employee_changes',
            'view_pensioners',
            'create_pensioners',
            'edit_pensioners',
            'delete_pensioners',
            'manage_pensioners',
            'view_roles',
            'manage_roles',
            'view_promotions',
            'manage_promotions',
            'approve_promotions',
            'reject_promotions',
            'view_profile',
            'view_loans',
            'manage_loans',
            'view_leaves',
            'manage_leaves',
            'approve_leaves',
            'view_probation',
            'manage_probation',
            'approve_probation',
            'reject_probation',
            'start_probation',
            'extend_probation',
        ]);

        // Employee role
        $employeeRole = Role::firstOrCreate(['name' => 'employee']);
        $employeeRole->givePermissionTo([
            'view_payroll',
            'view_payslips',
            'view_profile',
            'edit_profile',
            'change_password',
            'view_leaves',
            'create_leaves',
        ]);
    }
}