@extends('layouts.app')

@section('title', 'Report Details')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="card-title">Report Details</h3>
                    <div class="btn-group">
                        <a href="{{ route('reports.download', $report) }}" class="btn btn-success">
                            <i class="fas fa-download"></i> Download Report
                        </a>
                        <a href="{{ route('reports.index') }}" class="btn btn-secondary">
                            <i class="fas fa-arrow-left"></i> Back to Reports
                        </a>
                    </div>
                </div>
                
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <tr>
                                    <th>Report ID:</th>
                                    <td>{{ $report->report_id }}</td>
                                </tr>
                                <tr>
                                    <th>Report Type:</th>
                                    <td>
                                        <span class="badge bg-info">
                                            {{ $report->description }}
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Generated By:</th>
                                    <td>{{ $report->generatedBy->username ?? 'System' }}</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <tr>
                                    <th>Generated Date:</th>
                                    <td>{{ $report->generated_date->format('Y-m-d H:i:s') }}</td>
                                </tr>
                                <tr>
                                    <th>Export Format:</th>
                                    <td>
                                        <span class="badge bg-{{ $report->export_format === 'PDF' ? 'danger' : 'success' }}">
                                            {{ $report->export_format }}
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>File Status:</th>
                                    <td>
                                        @if($report->file_path && file_exists(storage_path('app/' . $report->file_path)))
                                            <span class="badge bg-success">Available</span>
                                        @else
                                            <span class="badge bg-danger">File Missing</span>
                                        @endif
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    
                    @if($report->report_data)
                        <div class="mt-4">
                            <h5>Report Data Preview</h5>
                            <div class="row">
                                <div class="col-md-12">
                                    <pre class="bg-light p-3 rounded" style="max-height: 400px; overflow-y: auto;">
                                        {{ json_encode($report->report_data, JSON_PRETTY_PRINT) }}
                                    </pre>
                                </div>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection