<?php $__env->startSection('title', 'Reports'); ?>

<?php $__env->startSection('content'); ?>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="card-title">Generated Reports</h3>
                    <div class="btn-group">
                        <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('generate_reports')): ?>
                        <a href="<?php echo e(route('reports.comprehensive.index')); ?>" class="btn btn-primary">
                            <i class="fas fa-chart-bar"></i> Comprehensive Reports
                        </a>
                        <?php endif; ?>
                        <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('generate_reports')): ?>
                        <a href="<?php echo e(route('reports.create')); ?>" class="btn btn-secondary">
                            <i class="fas fa-plus"></i> Generate individual Report
                        </a>
                        <?php endif; ?>
                    </div>
                </div>
                
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Report ID</th>
                                    <th>Employee</th>
                                    <th>Report Type</th>
                                    <th>Generated By</th>
                                    <th>Generated Date</th>
                                    <th>Format</th>
                                    <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('download_reports')): ?>
                                    <th>Actions</th>
                                    <?php endif; ?>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $__empty_1 = true; $__currentLoopData = $reports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $report): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                                    <tr>
                                        <td><?php echo e($report->report_id); ?></td>
                                        <td>
                                            <?php if($report->employee): ?>
                                                <?php echo e($report->employee->first_name); ?> <?php echo e($report->employee->surname); ?>

                                                <br>
                                                <small class="text-muted">Staff No: <?php echo e($report->employee->staff_no ?? $report->employee->employee_id); ?></small>
                                            <?php else: ?>
                                                <span class="text-muted">N/A</span>
                                            <?php endif; ?>
                                        </td>
                                        <td>
                                            <span class="badge bg-info text-dark">
                                                <?php echo e(ucfirst($report->display_type ?? $report->report_type)); ?>

                                            </span>
                                        </td>
                                        <td>
                                            <?php if($report->generatedBy && $report->generatedBy->user_id === auth()->id()): ?>
                                                <span class="text-primary fw-bold">You</span>
                                            <?php elseif($report->generatedBy): ?>
                                                <?php echo e($report->generatedBy->name); ?>

                                            <?php else: ?>
                                                <span class="text-muted">System</span>
                                            <?php endif; ?>
                                        </td>
                                        <td><?php echo e($report->generated_date->format('Y-m-d H:i:s')); ?></td>
                                        <td>
                                            <span class="badge bg-info text-dark">
                                                <?php echo e($report->export_format); ?>

                                            </span>
                                        </td>
                                        <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('generate_reports')): ?>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                
                                                <a href="<?php echo e(route('reports.download', $report)); ?>" class="btn btn-outline-success">
                                                    <i class="fas fa-download"></i> Download
                                                </a>
                                            </div>
                                        </td>
                                        <?php endif; ?>
                                    </tr>
                                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                                    <tr>
                                        <td colspan="7" class="text-center py-4">
                                            <div class="text-muted">
                                                <i class="fas fa-file-alt fa-3x mb-3"></i>
                                                <p>No reports generated yet.</p>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                    
                   <?php echo e($reports->links('pagination::bootstrap-5')); ?>


                </div>
            </div>
        </div>
    </div>
</div>

<!-- Generate Report Modal -->
<div class="modal fade" id="generateReportModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Generate Employee Report</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form id="generateReportForm" method="POST">
                <?php echo csrf_field(); ?>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="employee_id" class="form-label">Employee</label>
                                <select class="form-select" id="employee_id" name="employee_id" required>
                                    <option value="">Select Employee</option>
                                    <?php
                                        $allEmployees = \App\Models\Employee::with('department')->orderBy('first_name')->get();
                                    ?>
                                    <?php $__currentLoopData = $allEmployees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $employee): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                        <option value="<?php echo e($employee->employee_id); ?>">
                                            <?php echo e($employee->first_name); ?> <?php echo e($employee->surname); ?> (<?php echo e($employee->employee_number); ?>) - <?php echo e($employee->department->department_name ?? 'N/A'); ?>

                                        </option>
                                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                                    <!-- This would be populated via AJAX or server-side -->
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="report_type" class="form-label">Report Type</label>
                                <select class="form-select" id="report_type" name="report_type" required>
                                    <option value="">Select Report Type</option>
                                    <option value="comprehensive">Comprehensive Report</option>
                                    <option value="payroll">Payroll Report</option>
                                    <option value="disciplinary">Disciplinary Report</option>
                                    <option value="performance">Performance Report</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="export_format" class="form-label">Export Format</label>
                                <select class="form-select" id="export_format" name="export_format" required>
                                    <option value="">Select Format</option>
                                    <option value="PDF">PDF</option>
                                    <option value="Excel">Excel</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label class="form-label">Include Sections (Optional)</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="disciplinary" id="include_disciplinary">
                                    <label class="form-check-label" for="include_disciplinary">Disciplinary Records</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="payroll" id="include_payroll">
                                    <label class="form-check-label" for="include_payroll">Payroll Information</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="performance" id="include_performance">
                                    <label class="form-check-label" for="include_performance">Performance History</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="audit" id="include_audit">
                                    <label class="form-check-label" for="include_audit">Audit Trail</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="notifications" id="include_notifications">
                                    <label class="form-check-label" for="include_notifications">Notifications</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="retirement" id="include_retirement">
                                    <label class="form-check-label" for="include_retirement">Retirement Information</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-cog fa-spin d-none" id="loading-spinner"></i>
                        Generate Report
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('generateReportForm');
    const spinner = document.getElementById('loading-spinner');
    const submitBtn = form.querySelector('button[type="submit"]');
    
    // Load employees via AJAX
    fetch('/api/employees')
        .then(response => response.json())
        .then(data => {
            const select = document.getElementById('employee_id');
            data.forEach(employee => {
                const option = document.createElement('option');
                option.value = employee.employee_id;
                option.textContent = `${employee.first_name} (${employee.employee_id})`;
                select.appendChild(option);
            });
        });
    
    form.addEventListener('submit', function(e) {
        e.preventDefault();
        
        const employeeId = document.getElementById('employee_id').value;
        if (!employeeId) {
            alert('Please select an employee');
            return;
        }
        
        // Show loading state
        spinner.classList.remove('d-none');
        submitBtn.disabled = true;
        
        const formData = new FormData(form);
        
        fetch(`/reports/employee/${employeeId}/generate`, {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRF-TOKEN': document.querySelector('input[name="_token"]').value
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                alert('Report generated successfully!');
                window.location.href = data.download_url;
                bootstrap.Modal.getInstance(document.getElementById('generateReportModal')).hide();
            } else {
                alert('Error generating report: ' + (data.message || 'Unknown error'));
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Error generating report. Please try again.');
        })
        .finally(() => {
            spinner.classList.add('d-none');
            submitBtn.disabled = false;
        });
    });
});
</script>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Rowwww\Herd\hrm_payroll_system_design\resources\views/reports/index.blade.php ENDPATH**/ ?>