@extends('layouts.app')

@section('title', 'Reports')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="card-title">Generated Reports</h3>
                    <div class="btn-group">
                        @can('generate_reports')
                        <a href="{{ route('reports.comprehensive.index') }}" class="btn btn-primary">
                            <i class="fas fa-chart-bar"></i> Comprehensive Reports
                        </a>
                        @endcan
                        @can('generate_reports')
                        <a href="{{ route('reports.create') }}" class="btn btn-secondary">
                            <i class="fas fa-plus"></i> Generate Old Report
                        </a>
                        @endcan
                    </div>
                </div>
                
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Report ID</th>
                                    <th>Employee</th>
                                    <th>Report Type</th>
                                    <th>Generated By</th>
                                    <th>Generated Date</th>
                                    <th>Format</th>
                                    @can('download_reports')
                                    <th>Actions</th>
                                    @endcan
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($reports as $report)
                                    <tr>
                                        <td>{{ $report->report_id }}</td>
                                        <td>
                                            @if($report->employee)
                                                {{ $report->employee->first_name }} {{ $report->employee->surname }}
                                                <br>
                                                <small class="text-muted">ID: {{ $report->employee->employee_id }}</small>
                                            @else
                                                <span class="text-muted">N/A</span>
                                            @endif
                                        </td>
                                        <td>
                                            <span class="badge bg-info text-dark">
                                                {{ ucfirst($report->display_type ?? $report->report_type) }}
                                            </span>
                                        </td>
                                        <td>
                                            @if($report->generatedBy && $report->generatedBy->user_id === auth()->id())
                                                <span class="text-primary fw-bold">You</span>
                                            @elseif($report->generatedBy)
                                                {{ $report->generatedBy->name }}
                                            @else
                                                <span class="text-muted">System</span>
                                            @endif
                                        </td>
                                        <td>{{ $report->generated_date->format('Y-m-d H:i:s') }}</td>
                                        <td>
                                            <span class="badge bg-info text-dark">
                                                {{ $report->export_format }}
                                            </span>
                                        </td>
                                        @can('generate_reports')
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                
                                                <a href="{{ route('reports.download', $report) }}" class="btn btn-outline-success">
                                                    <i class="fas fa-download"></i> Download
                                                </a>
                                            </div>
                                        </td>
                                        @endcan
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="7" class="text-center py-4">
                                            <div class="text-muted">
                                                <i class="fas fa-file-alt fa-3x mb-3"></i>
                                                <p>No reports generated yet.</p>
                                            </div>
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    
                   {{ $reports->links('pagination::bootstrap-5') }}

                </div>
            </div>
        </div>
    </div>
</div>

<!-- Generate Report Modal -->
<div class="modal fade" id="generateReportModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Generate Employee Report</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <form id="generateReportForm" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="employee_id" class="form-label">Employee</label>
                                <select class="form-select" id="employee_id" name="employee_id" required>
                                    <option value="">Select Employee</option>
                                    @php
                                        $allEmployees = \App\Models\Employee::with('department')->orderBy('first_name')->get();
                                    @endphp
                                    @foreach($allEmployees as $employee)
                                        <option value="{{ $employee->employee_id }}">
                                            {{ $employee->first_name }} {{ $employee->surname }} ({{ $employee->employee_number }}) - {{ $employee->department->department_name ?? 'N/A' }}
                                        </option>
                                    @endforeach
                                    <!-- This would be populated via AJAX or server-side -->
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="report_type" class="form-label">Report Type</label>
                                <select class="form-select" id="report_type" name="report_type" required>
                                    <option value="">Select Report Type</option>
                                    <option value="comprehensive">Comprehensive Report</option>
                                    <option value="payroll">Payroll Report</option>
                                    <option value="disciplinary">Disciplinary Report</option>
                                    <option value="performance">Performance Report</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="export_format" class="form-label">Export Format</label>
                                <select class="form-select" id="export_format" name="export_format" required>
                                    <option value="">Select Format</option>
                                    <option value="PDF">PDF</option>
                                    <option value="Excel">Excel</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label class="form-label">Include Sections (Optional)</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="disciplinary" id="include_disciplinary">
                                    <label class="form-check-label" for="include_disciplinary">Disciplinary Records</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="payroll" id="include_payroll">
                                    <label class="form-check-label" for="include_payroll">Payroll Information</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="performance" id="include_performance">
                                    <label class="form-check-label" for="include_performance">Performance History</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="audit" id="include_audit">
                                    <label class="form-check-label" for="include_audit">Audit Trail</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="notifications" id="include_notifications">
                                    <label class="form-check-label" for="include_notifications">Notifications</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="include_sections[]" value="retirement" id="include_retirement">
                                    <label class="form-check-label" for="include_retirement">Retirement Information</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-cog fa-spin d-none" id="loading-spinner"></i>
                        Generate Report
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('generateReportForm');
    const spinner = document.getElementById('loading-spinner');
    const submitBtn = form.querySelector('button[type="submit"]');
    
    // Load employees via AJAX
    fetch('/api/employees')
        .then(response => response.json())
        .then(data => {
            const select = document.getElementById('employee_id');
            data.forEach(employee => {
                const option = document.createElement('option');
                option.value = employee.employee_id;
                option.textContent = `${employee.first_name} (${employee.employee_id})`;
                select.appendChild(option);
            });
        });
    
    form.addEventListener('submit', function(e) {
        e.preventDefault();
        
        const employeeId = document.getElementById('employee_id').value;
        if (!employeeId) {
            alert('Please select an employee');
            return;
        }
        
        // Show loading state
        spinner.classList.remove('d-none');
        submitBtn.disabled = true;
        
        const formData = new FormData(form);
        
        fetch(`/reports/employee/${employeeId}/generate`, {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRF-TOKEN': document.querySelector('input[name="_token"]').value
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                alert('Report generated successfully!');
                window.location.href = data.download_url;
                bootstrap.Modal.getInstance(document.getElementById('generateReportModal')).hide();
            } else {
                alert('Error generating report: ' + (data.message || 'Unknown error'));
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Error generating report. Please try again.');
        })
        .finally(() => {
            spinner.classList.add('d-none');
            submitBtn.disabled = false;
        });
    });
});
</script>
@endsection