@extends('layouts.app')

@section('title', 'Report Details')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="card-title">Report Details</h3>
                    <div class="btn-group">
                        <a href="{{ route('reports.download', $report) }}" class="btn btn-success">
                            <i class="fas fa-download"></i> Download Report
                        </a>
                        <a href="{{ route('reports.index') }}" class="btn btn-secondary">
                            <i class="fas fa-arrow-left"></i> Back to Reports
                        </a>
                    </div>
                </div>
                @if($report->report_type === 'comprehensive')
                    <div class="card-header bg-primary text-white">
                        <h4 class="mb-0"><i class="fas fa-chart-bar"></i> Comprehensive Report Summary</h4>
                    </div>
                @else
                    <div class="card-header bg-secondary text-white">
                        <h4 class="mb-0"><i class="fas fa-file-alt"></i> Basic Report Summary</h4>
                    </div>
                @endif
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <tr>
                                    <th>Report ID:</th>
                                    <td>{{ $report->report_id }}</td>
                                </tr>
                                <tr>
                                    <th>Report Type:</th>
                                    <td>
                                        <span class="badge badge-{{ $report->report_type === 'comprehensive' ? 'primary' : 'secondary' }}">
                                            {{ ucfirst($report->report_type) }}
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>Employee:</th>
                                    <td>
                                        @if($report->employee)
                                            {{ $report->employee->full_name }}
                                            <br>
                                            <small class="text-muted">ID: {{ $report->employee->employee_id }}</small>
                                        @else
                                            <span class="text-muted">N/A</span>
                                        @endif
                                    </td>
                                </tr>
                                <tr>
                                    <th>Generated By:</th>
                                    <td>{{ $report->generatedBy->username ?? 'System' }}</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <tr>
                                    <th>Generated Date:</th>
                                    <td>{{ $report->generated_date->format('Y-m-d H:i:s') }}</td>
                                </tr>
                                <tr>
                                    <th>Export Format:</th>
                                    <td>
                                        <span class="badge badge-{{ $report->export_format === 'PDF' ? 'danger' : 'success' }}">
                                            {{ $report->export_format }}
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>File Size:</th>
                                    <td>
                                        @if($report->file_path && file_exists(storage_path('app/' . $report->file_path)))
                                            {{ number_format(filesize(storage_path('app/' . $report->file_path)) / 1024, 2) }} KB
                                        @else
                                            <span class="text-muted">File not found</span>
                                        @endif
                                    </td>
                                </tr>
                                <tr>
                                    <th>Status:</th>
                                    <td>
                                        @if($report->file_path && file_exists(storage_path('app/' . $report->file_path)))
                                            <span class="badge badge-success">Available</span>
                                        @else
                                            <span class="badge badge-danger">File Missing</span>
                                        @endif
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    
                    @if($report->report_data)
                        <div class="mt-4">
                            <h5>Report Data Preview</h5>
                            <div class="accordion" id="reportDataAccordion">
                                @if(isset($report->report_data['employee_info']))
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="employeeInfoHeading">
                                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#employeeInfoCollapse">
                                                Employee Information
                                            </button>
                                        </h2>
                                        <div id="employeeInfoCollapse" class="accordion-collapse collapse show" data-bs-parent="#reportDataAccordion">
                                            <div class="accordion-body">
                                                <div class="row">
                                                    @foreach($report->report_data['employee_info'] as $key => $value)
                                                        <div class="col-md-6 mb-2">
                                                            <strong>{{ ucwords(str_replace('_', ' ', $key)) }}:</strong>
                                                            {{ $value ?? 'N/A' }}
                                                        </div>
                                                    @endforeach
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endif
                                
                                @if(isset($report->report_data['payroll_info']))
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="payrollInfoHeading">
                                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#payrollInfoCollapse">
                                                Payroll Information
                                            </button>
                                        </h2>
                                        <div id="payrollInfoCollapse" class="accordion-collapse collapse" data-bs-parent="#reportDataAccordion">
                                            <div class="accordion-body">
                                                <div class="row">
                                                    @foreach($report->report_data['payroll_info'] as $key => $value)
                                                        <div class="col-md-6 mb-2">
                                                            @if($key === 'basic_salary')
                                                                @php
                                                                    $label = isset($report->report_data['employee_info']['appointment_type']) && $report->report_data['employee_info']['appointment_type'] === 'Contract' ? 'Amount' : 'Basic Salary';
                                                                @endphp
                                                                <strong>{{ $label }}:</strong>
                                                                ₦{{ number_format($value, 2) }}
                                                            @elseif(in_array($key, ['net_salary']))
                                                                <strong>{{ ucwords(str_replace('_', ' ', $key)) }}:</strong>
                                                                ₦{{ number_format($value, 2) }}
                                                            @else
                                                                <strong>{{ ucwords(str_replace('_', ' ', $key)) }}:</strong>
                                                                {{ $value ?? 'N/A' }}
                                                            @endif
                                                        </div>
                                                    @endforeach
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endif
                                
                                @if(isset($report->report_data['disciplinary_records']) && count($report->report_data['disciplinary_records']) > 0)
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="disciplinaryHeading">
                                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#disciplinaryCollapse">
                                                Disciplinary Records ({{ count($report->report_data['disciplinary_records']) }})
                                            </button>
                                        </h2>
                                        <div id="disciplinaryCollapse" class="accordion-collapse collapse" data-bs-parent="#reportDataAccordion">
                                            <div class="accordion-body">
                                                <div class="table-responsive">
                                                    <table class="table table-sm">
                                                        <thead>
                                                            <tr>
                                                                <th>Date</th>
                                                                <th>Type</th>
                                                                <th>Description</th>
                                                                <th>Status</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            @foreach($report->report_data['disciplinary_records'] as $record)
                                                                <tr>
                                                                    <td>{{ $record['date'] }}</td>
                                                                    <td>{{ $record['type'] }}</td>
                                                                    <td>{{ $record['description'] }}</td>
                                                                    <td>
                                                                        <span class="badge badge-{{ $record['status'] === 'resolved' ? 'success' : 'warning' }}">
                                                                            {{ ucfirst($record['status']) }}
                                                                        </span>
                                                                    </td>
                                                                </tr>
                                                            @endforeach
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endif
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection