<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ComputeBeneficiary extends Model
{
    protected $table = 'compute_beneficiaries';

    protected $fillable = [
        'fulname',
        'lgaid',
        'gtype',
        'acc_no',
        'bankid',
        'reg_user',
        'reg_date',
        'stepid',
        'deptid',
        'mobile',
        'nxtkin_fulname',
        'nxtkin_mobile',
        'appt_date',
        'dod_r',
        'id_no',
        'period_yrs',
        'period_mnths',
        'period_days',
        'period_total_mnths',
        'basic_sal_annum',
        'basic_sal_mnth',
        'total_emolument',
        'pct_gratuity',
        'pct_pension',
        'gratuity_amt',
        'total_death_gratuity',
        'pension_per_annum',
        'pension_per_mnth',
        'accrued_pension',
        'accrued_pension_yrs',
        'apportion_fg_pct',
        'apportion_state_pct',
        'apportion_lga_pct',
        'apportion_fg_amt',
        'apportion_state_amt',
        'apportion_lga_amt',
        'sscale_circular_id',
        'is_elevated_service_yrs',
        'service_yrs_for_compute',
        'status',
        'approval_date',
        'open_file_no',
        'secret_file_no',
        'dob',
        'overstay_remark',
        'rank',
        'rankid',
        'salary_scale_id',
    ];

    protected $casts = [
        'reg_date' => 'datetime',
        'appt_date' => 'date',
        'dod_r' => 'date',
        'dob' => 'date',
        'approval_date' => 'datetime',
        'period_yrs' => 'integer',
        'period_mnths' => 'integer',
        'period_days' => 'integer',
        'period_total_mnths' => 'integer',
        'basic_sal_annum' => 'decimal:2',
        'basic_sal_mnth' => 'decimal:2',
        'total_emolument' => 'decimal:2',
        'pct_gratuity' => 'integer',
        'pct_pension' => 'integer',
        'gratuity_amt' => 'decimal:2',
        'total_death_gratuity' => 'decimal:2',
        'pension_per_annum' => 'decimal:2',
        'pension_per_mnth' => 'decimal:2',
        'accrued_pension' => 'decimal:2',
        'accrued_pension_yrs' => 'integer',
        'apportion_fg_pct' => 'integer',
        'apportion_state_pct' => 'integer',
        'apportion_lga_pct' => 'integer',
        'apportion_fg_amt' => 'decimal:2',
        'apportion_state_amt' => 'decimal:2',
        'apportion_lga_amt' => 'decimal:2',
        'is_elevated_service_yrs' => 'integer',
        'service_yrs_for_compute' => 'integer',
        'status' => 'integer',
    ];
}